context:
  version: 0.30.1
  default_abi_level: 1.26

package:
  name: themachinethatgoesping
  version: ${{ version }}

source:
  #path: ../
  git: https://github.com/themachinethatgoesping/themachinethatgoesping.git

build:
  script: 
    - export CPPFLAGS="-I$PREFIX/include $CPPFLAGS"  # [unix]
    - export LDFLAGS="-L$PREFIX/lib $LDFLAGS"        # [unix]
    - export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"  # [unix]
    - export BOOST_ROOT="$PREFIX"                    # [unix]
    - export MACOSX_DEPLOYMENT_TARGET=11.0           # [osx]
    - export C="ccache $C"
    - export CXX="ccache $CXX"
    - ${{ PYTHON }} -m pip install . -v --config-settings=setup-args="-Ddynamic_boost=enabled"
  number: 0
  # environment:
  #   - CPPFLAGS=-I$PREFIX/include          # [unix]
  #   - LDFLAGS=-L$PREFIX/lib               # [unix]
  #   - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig  # [unix]
  #   - BOOST_ROOT=$PREFIX

requirements:
  build:
    - meson>=1.8.1
    - ninja
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkgconfig
  host:
  - python >=3.11
  - meson-python>=0.15.0,<0.20.0
  - pybind11>=2.13.2,<2.14.0
  - numpy>=2.0.0,<2.5
  - pip
  - boost-cpp >=1.81.0,<1.84.0
  run:
  - ${{ pin_compatible('python') }}
  - ${{ pin_compatible('numpy') }}
  - ${{ pin_compatible('boost-cpp') }}
  - ipywidgets
  - matplotlib
  - numba
  - pandas
  - rasterio
  - tqdm
  - scipy
  - pytimeparse2

tests:
- python:
    imports:
    - themachinethatgoesping
    pip_check: true


about:
  #home: https://github.com/themachinethatgoesping
  summary: Enable advanced processing for multibeam and singlebeam echosounder data. THIS PROJECT IS IN DEVELOPMENT.
  license: MPL-2.0
  license_file: LICENSE

# maintainers:
#   - Peter Urban