# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  jobs:
    post_checkout:
      # add git lfs support (https://docs.readthedocs.io/en/stable/build-customization.html)
      - wget https://github.com/git-lfs/git-lfs/releases/download/v3.3.0/git-lfs-linux-amd64-v3.3.0.tar.gz
      - tar xvfz git-lfs-linux-amd64-v3.3.0.tar.gz
      - git config filter.lfs.process "`pwd`/git-lfs filter-process"
      - git config filter.lfs.smudge  "`pwd`/git-lfs smudge -- %f"
      - git config filter.lfs.clean "`pwd`/git-lfs clean -- %f"
      - ./git-lfs-3.3.0/git-lfs install
      - ./git-lfs-3.3.0/git-lfs fetch
      - ./git-lfs-3.3.0/git-lfs checkout

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
    - method: pip
      extra_requirements:
        - themachinethatgoesping
   - requirements: docs/requirements.txt
