context:
  version: "0.28.1"
  name: "themachinethatgoesping"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ./

build:
  #noarch: python-m
  script: pip install . -v --config-settings=setup-args="-Ddynamic_boost=enabled"
  number: 0

requirements:
  build:
    - meson>=1.4
    - meson-python
    - ninja
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkgconfig
    - pip
    - boost
    - python
    - numpy
    - pkg-config
    - cmake
    - curl
  host:
    - boost-cpp
    - python
    - numpy
# "build" packages picked up binutis 2.39 for gcc, but the "host" package picked up binutils 2.40 for python.
#   Force host to use same binutils as build by including them in here.
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
  run:
    - python
    - numba
    - ${{ pin_compatible('numpy') }}
    - tqdm
    - rasterio
    - matplotlib

tests:
  - python:
        imports:
            - themachinethatgoesping

about:
  repository: https://github.com/themachinethatgoesping
  summary: Enable advanced processing for multibeam and singlebeam echosounder data.THIS PROJECT IS IN DEVELOPMENT.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Peter Urban
