"""
Native Qt map viewer using pyqtgraph DockArea + extracted MapCore.

Provides a standalone Qt application for viewing maps without Jupyter.
The layout uses ``pyqtgraph.dockarea`` so the user can drag, float,
and rearrange panels.

Usage::

    from themachinethatgoesping.widgets.mapviewer_qt import MapViewerQt
    viewer = MapViewerQt(builder)
    viewer.show()
    viewer.run()   # blocks in QApplication.exec()
"""

import PySide6.QtCore
import PySide6.QtWidgets
import QtWidgets

from themachinethatgoesping.widgets.control_qt import (
    QtControlHandle as QtControlHandle,
    QtControlPanel as QtControlPanel,
    create_qt_control as create_qt_control
)
from themachinethatgoesping.widgets.control_spec import (
    CheckboxSpec as CheckboxSpec,
    DropdownSpec as DropdownSpec
)
from themachinethatgoesping.widgets.mapviewer_core import (
    LayerRenderSettings as LayerRenderSettings,
    MapCore as MapCore
)
import themachinethatgoesping.widgets.pyqtgraph_helpers as pgh


MAP_NAV_SPECS: list = ...

MAP_MISC_SPECS: list = ...

MAP_COLORBAR_SPECS: list = ...

MAP_MEASURE_SPECS: list = ...

MAP_COLORMAPS: list = ...

MAP_TAB_LAYOUT: dict = ...

class MapViewerQt(PySide6.QtWidgets.QMainWindow):
    """
    Standalone native Qt map viewer window.

    Parameters match :class:`MapViewerJupyter` so the two viewers are
    interchangeable at construction time.
    """

    def __init__(self, builder: Any = None, tile_builder: Any = None, width: int = 1000, height: int = 700, show_controls: bool = True, max_render_size: Tuple[int, int] = (2000, 2000), auto_update: bool = True, auto_update_delay_ms: int = 300, show: bool = True, embedded: bool = False, parent: Optional[QtWidgets.QWidget] = None) -> None: ...

    def build_control_widget(self) -> QtWidgets.QWidget:
        """Return all controls as a single embeddable QWidget."""

    def run(self) -> None:
        """Enter the Qt event loop (blocking)."""

    def set_layer_colormap(self, layer_name: str, colormap: str) -> 'MapViewerQt': ...

    def set_layer_opacity(self, layer_name: str, opacity: float) -> 'MapViewerQt': ...

    def set_layer_range(self, layer_name: str, vmin: float, vmax: float) -> 'MapViewerQt': ...

    def set_layer_blend_mode(self, layer_name: str, blend_mode: str) -> 'MapViewerQt': ...

    def set_tile_source(self, source_name: str) -> 'MapViewerQt': ...

    def set_tile_visible(self, visible: bool) -> 'MapViewerQt': ...

    @property
    def tile_builder(self): ...

    @tile_builder.setter
    def tile_builder(self, builder): ...

    def list_tile_sources(self) -> List[str]: ...

    def add_geotiff(self, path: str, name: Optional[str] = None, band: int = 1, **kwargs) -> 'MapViewerQt': ...

    def add_layer(self, backend: Any, name: Optional[str] = None, visible: bool = True, z_order: Optional[int] = None) -> 'MapViewerQt': ...

    def add_track(self, latitudes, longitudes, name: str = 'Track', color: Optional[str] = None, line_width: float = 2.0, is_active: bool = False, slot_idx: Optional[int] = None) -> None: ...

    def add_overview_track(self, overview, name: str = 'Overview', color: Optional[str] = None, **kwargs) -> None: ...

    def set_active_track(self, name: str) -> None: ...

    def clear_tracks(self) -> None: ...

    def set_track_color(self, name: str, color: str) -> None: ...

    def add_markers(self, latitudes, longitudes, name: str = 'markers', **kwargs): ...

    def add_markers_tuples(self, positions, name: str = 'markers', **kwargs): ...

    def remove_markers(self, name: str) -> None: ...

    def clear_markers(self) -> None: ...

    def update_ping_position(self, lat: float, lon: float) -> None: ...

    def zoom_to_fit(self) -> None: ...

    def zoom_to_track(self) -> None: ...

    def zoom_to_position(self, lat: float, lon: float, radius_deg: float = 0.01) -> None: ...

    def pan_to_wci_position(self) -> None: ...

    def pan_to_position(self, lat: float, lon: float) -> None: ...

    def is_position_near_edge(self, lat: float, lon: float, edge_fraction: float = 0.2) -> bool: ...

    def pan_to_position_if_near_edge(self, lat: float, lon: float, edge_fraction: float = 0.2) -> None: ...

    def connect_echogram_viewer(self, echogram_viewer) -> None: ...

    def connect_wci_viewer(self, wci_viewer) -> None: ...

    def refresh_tracks(self) -> None: ...

    def register_click_callback(self, callback: Callable[[float, float], None]) -> None: ...

    def register_view_change_callback(self, callback: Callable) -> None: ...

    def cleanup(self) -> None: ...

    def closeEvent(self, event) -> None: ...

    def __del__(self) -> None: ...

    staticMetaObject: PySide6.QtCore.QMetaObject = ...
