import ipywidgets.widgets.widget_box


class TqdmWidget(ipywidgets.widgets.widget_box.HBox):
    def __init__(self, **kwargs): ...

    def set_description(self, desc): ...

    def __call__(self, list_like, **kwargs): ...

    def __iter__(self): ...

    def __next__(self): ...

    def __len__(self): ...

    def update(self): ...

    def close(self): ...

    __annotations_cache__: dict = {}
