from themachinethatgoesping import echosounders as echosounders
from themachinethatgoesping.pingprocessing.watercolumn import (
    image as mi
)
from themachinethatgoesping.pingprocessing.watercolumn.helper import (
    make_image_helper as mi_hlp
)
from themachinethatgoesping.widgets.tqdmwidget import (
    TqdmWidget as TqdmWidget
)


WCI_VALUE_CHOICES: list = ...

class WCIViewer:
    def __init__(self, pings, horizontal_pixels=1024, name='WCI', figure=None, progress=None, show=True, cmap='YlGnBu_r', **kwargs): ...

    def set_ping_sample_selector(self, ping_sample_selector, apply_pss_to_bottom=False): ...

    def fix_xy(self, w): ...

    def unfix_xy(self, w): ...

    def update_data(self, w=None): ...

    def save_background(self): ...

    def update_view(self, w=None): ...

    def callback_view(self): ...

    def callback_data(self): ...
