"""
Jupyter notebook map viewer using the extracted core + ipywidgets controls.

Drop-in replacement for ``MapViewerPyQtGraph`` — same constructor signature,
same public API — but built on top of :class:`mapviewer_core.MapCore` and
:class:`control_jupyter.JupyterControlPanel`.
"""

import ipywidgets

from themachinethatgoesping.pingprocessing.widgets.control_jupyter import (
    JupyterControlHandle as JupyterControlHandle,
    JupyterControlPanel as JupyterControlPanel,
    create_jupyter_control as create_jupyter_control
)
from themachinethatgoesping.pingprocessing.widgets.control_spec import (
    CheckboxSpec as CheckboxSpec,
    DropdownSpec as DropdownSpec,
    FloatSliderSpec as FloatSliderSpec
)
from themachinethatgoesping.pingprocessing.widgets.mapviewer_core import (
    LayerRenderSettings as LayerRenderSettings,
    MapCore as MapCore
)
import themachinethatgoesping.pingprocessing.widgets.pyqtgraph_helpers as pgh


MAP_NAV_SPECS: list = ...

MAP_MISC_SPECS: list = ...

MAP_COLORBAR_SPECS: list = ...

MAP_COLORMAPS: list = ...

class MapViewerJupyter:
    """
    PyQtGraph-based map viewer for Jupyter notebooks.

    Features:
    - Interactive pan/zoom with mouse
    - Layer management with visibility/opacity/colorscale controls
    - Auto-update with debouncing on pan/zoom
    - Track overlays showing navigation paths from echograms
    - Current ping position marker
    - Integration with EchogramViewer and WCIViewer
    - Background tiles from web sources

    The constructor signature is compatible with ``MapViewerPyQtGraph``.
    """

    def __init__(self, builder: Any = None, tile_builder: Any = None, width: int = 800, height: int = 600, show_controls: bool = True, max_render_size: Tuple[int, int] = (2000, 2000), auto_update: bool = True, auto_update_delay_ms: int = 300, show: bool = True, embedded: bool = False) -> None: ...

    def build_control_widget(self) -> ipywidgets.Widget:
        """Return all controls as a single embeddable ipywidget."""

    def show(self) -> None:
        """Display the viewer widget."""

    def set_layer_colormap(self, layer_name: str, colormap: str) -> 'MapViewerJupyter': ...

    def set_layer_opacity(self, layer_name: str, opacity: float) -> 'MapViewerJupyter': ...

    def set_layer_range(self, layer_name: str, vmin: float, vmax: float) -> 'MapViewerJupyter': ...

    def set_layer_blend_mode(self, layer_name: str, blend_mode: str) -> 'MapViewerJupyter': ...

    def set_tile_source(self, source_name: str) -> 'MapViewerJupyter': ...

    def set_tile_visible(self, visible: bool) -> 'MapViewerJupyter': ...

    @property
    def tile_builder(self): ...

    @tile_builder.setter
    def tile_builder(self, builder): ...

    def list_tile_sources(self) -> List[str]: ...

    def add_geotiff(self, path: str, name: Optional[str] = None, band: int = 1, **kwargs) -> 'MapViewerJupyter': ...

    def add_layer(self, backend: Any, name: Optional[str] = None, visible: bool = True, z_order: Optional[int] = None) -> 'MapViewerJupyter': ...

    def add_track(self, latitudes, longitudes, name: str = 'Track', color: Optional[str] = None, line_width: float = 2.0, is_active: bool = False, slot_idx: Optional[int] = None) -> None: ...

    def add_overview_track(self, overview, name: str = 'Overview', color: Optional[str] = None, **kwargs) -> None: ...

    def set_active_track(self, name: str) -> None: ...

    def clear_tracks(self) -> None: ...

    def set_track_color(self, name: str, color: str) -> None: ...

    def add_markers(self, latitudes, longitudes, name: str = 'markers', **kwargs): ...

    def add_markers_tuples(self, positions, name: str = 'markers', **kwargs): ...

    def remove_markers(self, name: str) -> None: ...

    def clear_markers(self) -> None: ...

    def update_ping_position(self, lat: float, lon: float) -> None: ...

    def zoom_to_fit(self) -> None: ...

    def zoom_to_track(self) -> None: ...

    def zoom_to_position(self, lat: float, lon: float, radius_deg: float = 0.01) -> None: ...

    def pan_to_wci_position(self) -> None: ...

    def pan_to_position(self, lat: float, lon: float) -> None: ...

    def is_position_near_edge(self, lat: float, lon: float, edge_fraction: float = 0.2) -> bool: ...

    def pan_to_position_if_near_edge(self, lat: float, lon: float, edge_fraction: float = 0.2) -> None: ...

    def connect_echogram_viewer(self, echogram_viewer) -> None: ...

    def connect_wci_viewer(self, wci_viewer) -> None: ...

    def refresh_tracks(self) -> None: ...

    def register_click_callback(self, callback: Callable[[float, float], None]) -> None: ...

    def register_view_change_callback(self, callback: Callable) -> None: ...

    def cleanup(self) -> None: ...

    def __del__(self) -> None: ...
