// Auto-generated precompiled header
#pragma once

#include <Eigen/Core>
#include <Eigen/Eigen>
#include <Eigen/Geometry>
#include <GeographicLib/Constants.hpp>
#include <GeographicLib/Geocentric.hpp>
#include <GeographicLib/Geodesic.hpp>
#include <GeographicLib/GeodesicExact.hpp>
#include <GeographicLib/LocalCartesian.hpp>
#include <GeographicLib/UTMUPS.hpp>
#include <Python.h>
#include <algorithm>
#include <arm_neon.h>
#include <array>
#include <assert.h>
#include <atomic>
#include <bit>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string/find.hpp>
#include <boost/iostreams/concepts.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/math/interpolators/makima.hpp>
#include <cassert>
#include <cctype>
#include <cfloat>
#include <charconv>
#include <chrono>
#include <cinttypes>
#include <climits>
#include <cmath>
#include <complex>
#include <complex.h>
#include <concepts>
#include <crtdefs.h>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cxxabi.h>
#include <emmintrin.h>
#include <endian.h>
#include <exception>
#include <fmt/core.h>
#include <fmt/format.h>
#include <fmt/ostream.h>
#include <forward_list>
#include <frameobject.h>
#include <frozen/map.h>
#include <functional>
#include <initializer_list>
#include <intrin.h>
#include <io.h>
#include <iosfwd>
#include <iostream>
#include <istream>
#include <iterator>
#include <limits>
#include <limits.h>
#include <machine/endian.h>
#include <magic_enum/magic_enum.hpp>
#include <map>
#include <math.h>
#include <memory>
#include <mutex>
#include <new>
#include <npy_config.h>
#include <numbers>
#include <numeric>
#include <optional>
#include <pugixml.hpp>
#include <pybind11/attr.h>
#include <pybind11/gil.h>
#include <pybind11/iostream.h>
#include <pybind11/numpy.h>
#include <pybind11/options.h>
#include <pybind11/pybind11.h>
#include <pybind11/pytypes.h>
#include <pybind11/stl.h>
#include <pythread.h>
#include <set>
#include <sstream>
#include <stdexcept>
#include <stdfloat>
#include <streambuf>
#include <string>
#include <string_view>
#include <sys/byteorder.h>
#include <sys/endian.h>
#include <sys/types.h>
#include <system_error>
#include <tbb/tbb.h>
#include <thread>
#include <tuple>
#include <type_traits>
#include <typeindex>
#include <typeinfo>
#include <unistd.h>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>
#include <version>
#include <xsimd/xsimd.hpp>
#include <xtensor-python/pytensor.hpp>
#include <xtensor/containers/xadapt.hpp>
#include <xtensor/containers/xcontainer.hpp>
#include <xtensor/containers/xtensor.hpp>
#include <xtensor/views/xview.hpp>
#include <xtl/xclosure.hpp>
#include <xtl/xcompare.hpp>
#include <xtl/xcomplex.hpp>
#include <xtl/xdynamic_bitset.hpp>
#include <xtl/xfunctional.hpp>
#include <xtl/xiterator_base.hpp>
#include <xtl/xmeta_utils.hpp>
#include <xtl/xoptional_sequence.hpp>
#include <xtl/xsequence.hpp>
#include <xtl/xspan_impl.hpp>
#include <xtl/xtype_traits.hpp>
#include <xtl/xvariant.hpp>
#include <xxhash.hpp>
#include <yvals.h>
