// Auto-generated precompiled header
#pragma once

#include <Eigen/Core>
#include <Eigen/Eigen>
#include <Eigen/Geometry>
#include <GeographicLib/Constants.hpp>
#include <GeographicLib/Geocentric.hpp>
#include <GeographicLib/Geodesic.hpp>
#include <GeographicLib/GeodesicExact.hpp>
#include <GeographicLib/LocalCartesian.hpp>
#include <GeographicLib/UTMUPS.hpp>
#include <algorithm>
#include <arm_neon.h>
#include <array>
#include <bit>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string/find.hpp>
#include <boost/iostreams/concepts.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/math/interpolators/makima.hpp>
#include <cassert>
#include <cctype>
#include <cfloat>
#include <charconv>
#include <chrono>
#include <cinttypes>
#include <climits>
#include <cmath>
#include <complex>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <emmintrin.h>
#include <endian.h>
#include <exception>
#include <fmt/core.h>
#include <fmt/format.h>
#include <fmt/ostream.h>
#include <fmt/ranges.h>
#include <frozen/map.h>
#include <functional>
#include <initializer_list>
#include <intrin.h>
#include <iosfwd>
#include <iostream>
#include <istream>
#include <iterator>
#include <limits>
#include <machine/endian.h>
#include <magic_enum/magic_enum.hpp>
#include <map>
#include <math.h>
#include <memory>
#include <nanobind/nanobind.h>
#include <nanobind/nb_python.h>
#include <nanobind/ndarray.h>
#include <nanobind/operators.h>
#include <nanobind/stl/pair.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/string_view.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/variant.h>
#include <nanobind/stl/vector.h>
#include <new>
#include <numbers>
#include <numeric>
#include <optional>
#include <pugixml.hpp>
#include <set>
#include <sstream>
#include <stdexcept>
#include <stdfloat>
#include <streambuf>
#include <string>
#include <string_view>
#include <sys/byteorder.h>
#include <sys/endian.h>
#include <system_error>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>
#include <version>
#include <xtensor/containers/xadapt.hpp>
#include <xtensor/containers/xarray.hpp>
#include <xtensor/containers/xbuffer_adaptor.hpp>
#include <xtensor/containers/xcontainer.hpp>
#include <xtensor/containers/xscalar.hpp>
#include <xtensor/containers/xtensor.hpp>
#include <xtensor/core/xassign.hpp>
#include <xtensor/core/xeval.hpp>
#include <xtensor/core/xfunction.hpp>
#include <xtensor/reducers/xreducer.hpp>
#include <xtensor/views/xindex_view.hpp>
#include <xtensor/views/xview.hpp>
#include <xtl/xsequence.hpp>
#include <xxhash.hpp>
