// Auto-generated precompiled header
#pragma once

#include <Eigen/Core>
#include <Eigen/Eigen>
#include <Eigen/Geometry>
#include <algorithm>
#include <array>
#include <atomic>
#include <boost/algorithm/string.hpp>
#include <boost/iostreams/concepts.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/math/interpolators/makima.hpp>
#include <chrono>
#include <cmath>
#include <complex>
#include <concepts>
#include <fmt/core.h>
#include <fmt/format.h>
#include <fmt/ostream.h>
#include <fmt/ranges.h>
#include <fmt/std.h>
#include <frozen/map.h>
#include <indicators/block_progress_bar.hpp>
#include <indicators/progress_spinner.hpp>
#include <iomanip>
#include <iosfwd>
#include <iostream>
#include <istream>
#include <limits>
#include <magic_enum/magic_enum.hpp>
#include <memory>
#include <numbers>
#include <numeric>
#include <optional>
#include <ranges>
#include <set>
#include <sstream>
#include <stdexcept>
#include <streambuf>
#include <string>
#include <string_view>
#include <thread>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>
#include <xtensor/containers/xcontainer.hpp>
#include <xtensor/containers/xtensor.hpp>
#include <xxhash.hpp>
