// Auto-generated precompiled header
#pragma once

#include <Eigen/Core>
#include <Eigen/Eigen>
#include <Eigen/Geometry>
#include <algorithm>
#include <arm_neon.h>
#include <array>
#include <atomic>
#include <bit>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string/find.hpp>
#include <boost/iostreams/concepts.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/math/interpolators/makima.hpp>
#include <cassert>
#include <cctype>
#include <cfloat>
#include <chrono>
#include <cinttypes>
#include <climits>
#include <cmath>
#include <complex>
#include <concepts>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <emmintrin.h>
#include <endian.h>
#include <fmt/core.h>
#include <fmt/format.h>
#include <fmt/ostream.h>
#include <frozen/map.h>
#include <indicators/block_progress_bar.hpp>
#include <indicators/progress_spinner.hpp>
#include <intrin.h>
#include <iostream>
#include <istream>
#include <iterator>
#include <limits>
#include <machine/endian.h>
#include <magic_enum/magic_enum.hpp>
#include <memory>
#include <numbers>
#include <numeric>
#include <optional>
#include <pugixml.hpp>
#include <pybind11/chrono.h>
#include <pybind11/eigen.h>
#include <pybind11/embed.h>
#include <pybind11/iostream.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <random>
#include <set>
#include <sstream>
#include <stdexcept>
#include <stdfloat>
#include <streambuf>
#include <string>
#include <string_view>
#include <sys/byteorder.h>
#include <sys/endian.h>
#include <system_error>
#include <thread>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>
#include <version>
#include <xtensor-python/pytensor.hpp>
#include <xtensor/containers/xtensor.hpp>
#include <xtensor/views/xview.hpp>
#include <xxhash.hpp>
