// Auto-generated precompiled header
// Target: echosounders:echosounders_cppy
#pragma once

#include <pybind11/stl.h>
#include <pybind11/iostream.h>
#include <pybind11/pybind11.h>
#include <vector>
#include <magic_enum/magic_enum.hpp>
#include <fmt/core.h>
#include <unordered_map>
#include <xtensor-python/pytensor.hpp>
#include <set>
#include <string>
#include <complex>
#include <iostream>
#include <map>
#include <limits>
#include <filesystem>
#include <fstream>
#include <boost/iostreams/stream.hpp>
#include <memory>
#include <deque>
#include <boost/sort/sort.hpp>
#include <boost/iostreams/device/mapped_file.hpp>
#include <xtensor/views/xview.hpp>
#include <xtensor/containers/xadapt.hpp>
#include <string_view>
#include <xtensor-python/xtensor_type_caster_base.hpp>
#include <xtensor/containers/xtensor.hpp>
#include <pybind11/pytypes.h>
#include <xxhash.hpp>
#include <chrono>
#include <boost/flyweight.hpp>
#include <array>
#include <sstream>
#include <Eigen/Core>
#include <stdexcept>
#include <variant>
#include <cmath>
#include <xtensor/io/xio.hpp>
#include <Eigen/Dense>
#include <bitset>
#include <boost/algorithm/string.hpp>
#include <pugixml.hpp>
#include <iosfwd>
#include <optional>
#include <boost/unordered_map.hpp>
#include <boost/flyweight/key_value.hpp>
#include <pybind11/complex.h>
#include <fmt/format.h>
#include <fmt/ostream.h>
#include <xtensor/core/xshape.hpp>
#include <utility>
#include <algorithm>
#include <xtensor/core/xmath.hpp>
#include <numbers>
#include <xtensor/misc/xmanipulation.hpp>
#include <tuple>
#include <cstdint>
#include <xtensor/views/xindex_view.hpp>
#include <frozen/map.h>
#include <frozen/unordered_map.h>
#include <frozen/string.h>
#include <stdint.h>
