// Auto-generated precompiled header
// Target: echosounders:themachinethatgoesping_echosounders
#pragma once

#include <vector>
#include <unordered_map>
#include <string>
#include <fmt/core.h>
#include <set>
#include <iostream>
#include <magic_enum/magic_enum.hpp>
#include <complex>
#include <map>
#include <xtensor/views/xview.hpp>
#include <xtensor/containers/xadapt.hpp>
#include <limits>
#include <fstream>
#include <filesystem>
#include <boost/iostreams/stream.hpp>
#include <string_view>
#include <xtensor/containers/xtensor.hpp>
#include <deque>
#include <boost/iostreams/device/mapped_file.hpp>
#include <memory>
#include <boost/flyweight.hpp>
#include <xxhash.hpp>
#include <pugixml.hpp>
#include <stdexcept>
#include <boost/sort/sort.hpp>
#include <iosfwd>
#include <array>
#include <optional>
#include <fmt/format.h>
#include <cmath>
#include <boost/flyweight/key_value.hpp>
#include <Eigen/Core>
#include <xtensor/io/xio.hpp>
#include <sstream>
#include <boost/algorithm/string.hpp>
#include <cstdint>
#include <variant>
#include <bitset>
#include <algorithm>
#include <Eigen/Dense>
#include <utility>
#include <xtensor/core/xshape.hpp>
#include <xtensor/core/xmath.hpp>
#include <numbers>
#include <xtensor/misc/xmanipulation.hpp>
#include <boost/unordered_map.hpp>
#include <xtensor/views/xindex_view.hpp>
#include <boost/algorithm/string/find.hpp>
#include <cstring>
#include <boost/endian/conversion.hpp>
#include <ostream>
#include <fmt/ostream.h>
#include <istream>
