"""Module that holds functions used for image processing functions"""

from typing import Annotated, overload

import numpy
from numpy.typing import NDArray


@overload
def find_local_maxima(data: Annotated[NDArray[numpy.float64], dict(shape=(None, None, None), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[int], list[float]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[float]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[float]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.float32], dict(shape=(None, None, None), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[int], list[float]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[float]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[float]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[int], list[int]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[int]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[int], list[int]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[int]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[int], list[int]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[int]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[int], list[int]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int], list[int]]: ...

@overload
def find_local_maxima(data: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> tuple[list[int], list[int]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.float64], dict(shape=(None, None, None), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[int]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.float32], dict(shape=(None, None, None), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], threshold: float | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[int]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[int]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[int]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[int]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[Annotated[NDArray[numpy.int64], dict(order='C')]]: ...

@overload
def find_local_maxima2(data: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], threshold: int | None = None, accept_nans: bool = True, mp_cores: int = 1) -> list[int]: ...

class UniformAxis:
    @overload
    def __init__(self, origin: float, spacing: float, size: int) -> None: ...

    @overload
    def __init__(self, coordinates: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], tolerance: float = 1e-09) -> None: ...

    @overload
    def __init__(self, coordinates: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], tolerance: float = 1e-09) -> None: ...

    @property
    def origin(self) -> float: ...

    @origin.setter
    def origin(self, arg: float, /) -> None: ...

    @property
    def spacing(self) -> float: ...

    @spacing.setter
    def spacing(self, arg: float, /) -> None: ...

    @property
    def size(self) -> int: ...

    @size.setter
    def size(self, arg: int, /) -> None: ...

@overload
def backward_map_nearest(reference: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_nearest(reference: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_nearest(reference: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_nearest(reference: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_nearest(reference: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_nearest(reference: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_nearest(reference: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_nearest(reference: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_nearest(reference: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_nearest(reference: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_nearest(reference: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_nearest_add(reference: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_nearest_add(reference: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_nearest_add(reference: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_nearest_add(reference: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_nearest_add(reference: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_nearest_add(reference: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_nearest_add(reference: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_nearest_add(reference: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_nearest_add(reference: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_nearest_add(reference: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_nearest_add(reference: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_bilinear(reference: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_bilinear(reference: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_bilinear(reference: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_bilinear(reference: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_bilinear(reference: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_bilinear(reference: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_bilinear(reference: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_bilinear(reference: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_bilinear(reference: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_bilinear(reference: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_bilinear(reference: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], new_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')]: ...

@overload
def backward_map_bilinear_add(reference: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_bilinear_add(reference: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_bilinear_add(reference: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_bilinear_add(reference: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_bilinear_add(reference: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_bilinear_add(reference: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_bilinear_add(reference: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_bilinear_add(reference: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_bilinear_add(reference: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_bilinear_add(reference: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def backward_map_bilinear_add(reference: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], reference_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], reference_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], second_x: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], second_y: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], mp_cores: int = 1) -> None: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.float64], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.float64], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.float64], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.float64], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.float32], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.float32], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.float32], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.float32], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.float32], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.float32], dict(shape=(None,), order='C')], null_region: int = 0, threshold: float | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int64], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int64], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int64], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int32], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int32], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int16], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int16], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int16], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_volume: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], data_volume: Annotated[NDArray[numpy.int8], dict(shape=(None, None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], data_image: Annotated[NDArray[numpy.int8], dict(shape=(None, None), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...

@overload
def grow_regions(region_vector: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], data_vector: Annotated[NDArray[numpy.int8], dict(shape=(None,), order='C')], null_region: int = 0, threshold: int | None = None, force_negative_gradient: bool = True, eat_neighbor_regions: bool = False, mp_cores: int = 1) -> bool: ...
