import numba.core.registry

from themachinethatgoesping.algorithms_nanopy.gridding import (
    ForwardGridder3D as ForwardGridder3D
)
from themachinethatgoesping.gridding.forwardgridderlegacy import (
    ForwardGridderLegacy as ForwardGridderLegacy
)
from themachinethatgoesping.gridding.forwardgridderlegacynew import (
    ForwardGridderLegacyNew as ForwardGridderLegacyNew
)
import themachinethatgoesping.gridding.functions.gridfunctions as gf


static_get_target_pos: numba.core.registry.CPUDispatcher = ...

class EchoGrid:
    @classmethod
    def from_data(cls, res, sx, sy, sz, sv, blockmean=False): ...

    @classmethod
    def from_dataF(cls, res, sx, sy, sz, sv, blockmean=False): ...

    @classmethod
    def from_data_legacy(cls, res, sx, sy, sz, sv, blockmean=False): ...

    @classmethod
    def from_data_legacy_new(cls, res, sx, sy, sz, sv, blockmean=False): ...

    def __init__(self, image_sums, image_nums, gridder): ...

    def get_target_pos(self, min_val=float('nan')): ...

    def get_total_value(self, min_val): ...

    def get_total_value_layer(self, min_val): ...

    def get_gridder(self): ...

    def cut_by_layer_size(self, layer_z, layer_size): ...

    def cut_by_layer_extent(self, min_z=None, max_z=None): ...

    def get_depth_mean_image(self, layer_z, layer_size): ...

    def get_grid_extent(self, axis='xyz'): ...

    def to_string(self, TrueValue, methodName=None, minMethodNameSize=None): ...

    def print(self, methodName, minMethodNameSize, TrueValue): ...

    def get_image(self, toDb=True, minDbVal=-50): ...

    def plot(self, figure, targets_color=None, target_size=1, show_wci=True, show_echo=True, show_map=True, show_colorbar=True, toDb=True, minDbVal=-50, minDbReplace=None, xindex=None, yindex=None, zindex=None, zindeces=None, kwargs=None, colorbar_kwargs=None): ...
