import themachinethatgoesping.echosounders as echosounders
from themachinethatgoesping.pingprocessing.core.asserts import (
    assert_length as assert_length,
    assert_valid_argument as assert_valid_argument
)
from themachinethatgoesping.pingprocessing.core.progress import (
    get_progress_iterator as get_progress_iterator
)
import themachinethatgoesping.pingprocessing.watercolumn.helper as wchelper
import themachinethatgoesping.tools as tools


class EchoData:
    def __init__(self, wc_data, times): ...

    def set_ping_numbers(self, ping_numbers): ...

    def set_ping_times(self, ping_times, time_zone=...): ...

    def set_range_extent(self, min_ranges, max_ranges): ...

    def set_depth_extent(self, min_depths, max_depths): ...

    def add_ping_param(self, name, x_reference, y_reference, vec_x_val, vec_y_val): ...

    def get_ping_param(self, name, use_x_coordinates=False): ...

    @classmethod
    def from_pings(cls, pings, pss=..., wci_value: str = 'sv/av/pv/rv', linear_mean=True, no_navigation=False, apply_pss_to_bottom=False, verbose=True): ...

    def concat(cls, echodata_list): ...

    @staticmethod
    def sample_y_coordinates(vec_min_y, vec_max_y, vec_res_y, min_y, max_y, max_samples=2048): ...

    def reinit(self): ...

    def set_y_coordinates(self, name, y_coordinates, y_resolution, vec_min_y, vec_max_y): ...

    def get_filtered_by_y_extent(self, vec_x_val, vec_min_y, vec_max_y): ...

    def set_x_coordinates(self, name, x_coordinates, x_resolution, x_interpolation_limit, vec_x_val): ...

    def set_y_axis_sample_nr(self, min_sample_nr=0, max_sample_nr=float('nan'), max_samples=2048): ...

    def set_y_axis_depth(self, min_depth=float('nan'), max_depth=float('nan'), max_samples=2048): ...

    def set_y_axis_range(self, min_range=float('nan'), max_range=float('nan'), max_samples=2048): ...

    def set_x_axis_ping_nr(self, min_ping_nr=0, max_ping_nr=float('nan'), max_steps=8096): ...

    def set_x_axis_ping_time(self, min_timestamp=float('nan'), max_timestamp=float('nan'), time_resolution=float('nan'), time_interpolation_limit=float('nan'), max_steps=20000): ...

    def set_x_axis_date_time(self, min_ping_time=float('nan'), max_ping_time=float('nan'), time_resolution=float('nan'), time_interpolation_limit=float('nan'), max_steps=20000): ...

    def get_y_indices(self, wci_nr): ...

    def get_x_indices(self): ...

    def build_image(self, progress=None): ...
