import themachinethatgoesping as theping
from themachinethatgoesping.algorithms_nanopy.featuremapping import (
    NearestFeatureMapper as NearestFeatureMapper
)
from themachinethatgoesping.algorithms_nanopy.geoprocessing.functions import (
    to_raypoints as to_raypoints
)
from themachinethatgoesping.algorithms_nanopy.gridding import (
    ForwardGridder1D as ForwardGridder1D
)
import themachinethatgoesping.echosounders as echosounders
from themachinethatgoesping.pingprocessing.core.asserts import (
    assert_length as assert_length,
    assert_valid_argument as assert_valid_argument
)
from themachinethatgoesping.pingprocessing.core.progress import (
    get_progress_iterator as get_progress_iterator
)
from themachinethatgoesping.pingprocessing.watercolumn.echograms.layers.echolayer import (
    EchoLayer as EchoLayer,
    PingData as PingData
)
import themachinethatgoesping.pingprocessing.watercolumn.helper as wchelper
import themachinethatgoesping.tools as tools


class EchogramBuilder:
    def __init__(self, pings, times, beam_sample_selections, wci_value, linear_mean, depth_stack=False): ...

    def set_depth_stack(self, depth_stack=True): ...

    def set_range_stack(self, range_stack=True): ...

    def set_linear_mean(self, linear_mean): ...

    def set_ping_numbers(self, ping_numbers): ...

    def set_ping_times(self, ping_times, time_zone=...): ...

    def set_range_extent(self, min_ranges, max_ranges): ...

    def set_depth_extent(self, min_depths, max_depths): ...

    def set_sample_nr_extent(self, min_sample_nrs, max_sample_nrs): ...

    def add_ping_param(self, name, x_reference, y_reference, vec_x_val, vec_y_val): ...

    def get_ping_param(self, name, use_x_coordinates=False): ...

    def get_x_kwargs(self): ...

    def get_y_kwargs(self): ...

    @classmethod
    def from_pings(cls, pings, pss=..., wci_value: str = 'sv/av/pv/rv', linear_mean=True, no_navigation=False, apply_pss_to_bottom=False, force_angle=None, depth_stack=False, verbose=True): ...

    def get_wci_range_stack(self, nr): ...

    def get_wci_depth_stack(self, nr, from_bottom_xyz=False): ...

    def reinit(self): ...

    def set_y_coordinates(self, name, y_coordinates, vec_min_y, vec_max_y): ...

    def get_filtered_by_y_extent(self, vec_x_val, vec_min_y, vec_max_y): ...

    def copy_xy_axis(self, other): ...

    def set_x_coordinates(self, name, x_coordinates, x_interpolation_limit): ...

    def set_y_axis_y_indice(self, min_sample_nr=0, max_sample_nr=float('nan'), max_steps=1024, **kwargs): ...

    def set_y_axis_depth(self, min_depth=float('nan'), max_depth=float('nan'), max_steps=1024, **kwargs): ...

    def set_y_axis_range(self, min_range=float('nan'), max_range=float('nan'), max_steps=1024, **kwargs): ...

    def set_y_axis_sample_nr(self, min_sample_nr=0, max_sample_nr=float('nan'), max_steps=1024, **kwargs): ...

    def set_x_axis_ping_index(self, min_ping_index=0, max_ping_index=float('nan'), max_steps=4096, **kwargs): ...

    def set_x_axis_ping_time(self, min_timestamp=float('nan'), max_timestamp=float('nan'), time_resolution=float('nan'), time_interpolation_limit=float('nan'), max_steps=4096, **kwargs): ...

    def set_x_axis_date_time(self, min_ping_time=float('nan'), max_ping_time=float('nan'), time_resolution=float('nan'), time_interpolation_limit=float('nan'), max_steps=4096, **kwargs): ...

    def get_y_indices_range_stack(self, wci_nr): ...

    def get_y_indices_depth_stack(self, wci_nr, y_gridder=None): ...

    def get_x_indices(self): ...

    def build_image(self, progress=None): ...

    def build_image_and_layer_image(self, progress=None): ...

    def build_image_and_layer_images(self, progress=None): ...

    def get_wci_layers_range_stack(self, nr): ...

    def get_extent_layers(self, nr, axis_name=None): ...

    def get_limits_layers(self, nr, axis_name=None): ...

    def __set_layer__(self, name, layer): ...

    def add_layer(self, name, vec_x_val, vec_min_y, vec_max_y): ...

    def add_layer_from_static_layer(self, name, min_y, max_y): ...

    def add_layer_from_ping_param_offsets_absolute(self, name, ping_param_name, offset_0, offset_1): ...

    def add_layer_from_ping_param_offsets_relative(self, name, ping_param_name, offset_0, offset_1): ...

    def remove_layer(self, name): ...

    def clear_layers(self): ...

    def clear_main_layer(self): ...

    def iterate_ping_data(self, keep_to_xlimits=True): ...
