import themachinethatgoesping.algorithms_nanopy.amplitudecorrection as amplitudecorrection
import themachinethatgoesping.algorithms_nanopy.echogramprocessing as echogramprocessing
import themachinethatgoesping.algorithms_nanopy.featuremapping as featuremapping
import themachinethatgoesping.algorithms_nanopy.geoprocessing as geoprocessing
import themachinethatgoesping.algorithms_nanopy.gridding as gridding
import themachinethatgoesping.algorithms_nanopy.imageprocessing as imageprocessing
import themachinethatgoesping.algorithms_nanopy.pointprocessing as pointprocessing
import themachinethatgoesping.algorithms_nanopy.signalprocessing as signalprocessing
