"""Helper functions for the gridder class, implemented using numba"""

import numba.core.registry

import themachinethatgoesping.gridding.functions.helperfunctions as hlp


get_minmax: numba.core.registry.CPUDispatcher = ...

get_index: numba.core.registry.CPUDispatcher = ...

get_index_fraction: numba.core.registry.CPUDispatcher = ...

get_value: numba.core.registry.CPUDispatcher = ...

get_grd_value: numba.core.registry.CPUDispatcher = ...

get_index_weights: numba.core.registry.CPUDispatcher = ...

grd_weighted_mean: numba.core.registry.CPUDispatcher = ...

grd_block_mean: numba.core.registry.CPUDispatcher = ...
