from __future__ import annotations
from collections import defaultdict
from copy import deepcopy
import datetime as dt
import matplotlib as mpl
from matplotlib import dates as mdates
import numpy as np
from themachinethatgoesping.algorithms.geoprocessing.functions import to_raypoints
from themachinethatgoesping.algorithms.gridding import ForwardGridder1D
from themachinethatgoesping import echosounders
from themachinethatgoesping.pingprocessing.core.asserts import assert_length
from themachinethatgoesping.pingprocessing.core.asserts import assert_valid_argument
from themachinethatgoesping.pingprocessing.core.progress import get_progress_iterator
from themachinethatgoesping.pingprocessing.watercolumn.echograms.layers.echolayer import EchoLayer
from themachinethatgoesping.pingprocessing.watercolumn.echograms.layers.echolayer import PingData
from themachinethatgoesping.pingprocessing.watercolumn import helper as wchelper
from themachinethatgoesping import tools
from tqdm.asyncio import tqdm_asyncio as tqdm
import warnings as warnings
__all__ = ['EchoLayer', 'EchogramBuilder', 'ForwardGridder1D', 'PingData', 'assert_length', 'assert_valid_argument', 'deepcopy', 'defaultdict', 'dt', 'echosounders', 'get_progress_iterator', 'mdates', 'mpl', 'np', 'to_raypoints', 'tools', 'tqdm', 'warnings', 'wchelper']
class EchogramBuilder:
    @staticmethod
    def sample_y_coordinates(vec_min_y, vec_max_y, vec_res_y, min_y, max_y, max_steps = 1024):
        ...
    @classmethod
    def from_pings(cls, pings, pss = ..., wci_value: str = 'sv/av/pv/rv', linear_mean = True, no_navigation = False, apply_pss_to_bottom = False, force_angle = None, depth_stack = False, verbose = True):
        ...
    def __init__(self, pings, times, beam_sample_selections, wci_value, linear_mean, depth_stack = False):
        ...
    def __set_layer__(self, name, layer):
        ...
    def add_layer(self, name, vec_x_val, vec_min_y, vec_max_y):
        ...
    def add_layer_from_ping_param_offsets_absolute(self, name, ping_param_name, offset_0, offset_1):
        ...
    def add_layer_from_ping_param_offsets_relative(self, name, ping_param_name, offset_0, offset_1):
        ...
    def add_layer_from_static_layer(self, name, min_y, max_y):
        ...
    def add_ping_param(self, name, x_reference, y_reference, vec_x_val, vec_y_val):
        ...
    def build_image(self, progress = None):
        ...
    def build_image_and_layer_image(self, progress = None):
        ...
    def build_image_and_layer_images(self, progress = None):
        ...
    def clear_layers(self):
        ...
    def clear_main_layer(self):
        ...
    def copy_xy_axis(self, other):
        ...
    def get_extent_layers(self, nr, axis_name = None):
        ...
    def get_filtered_by_y_extent(self, vec_x_val, vec_min_y, vec_max_y):
        ...
    def get_limits_layers(self, nr, axis_name = None):
        ...
    def get_ping_param(self, name, use_x_coordinates = False):
        ...
    def get_wci_depth_stack(self, nr, from_bottom_xyz = False):
        ...
    def get_wci_layers_range_stack(self, nr):
        ...
    def get_wci_range_stack(self, nr):
        ...
    def get_x_indices(self):
        ...
    def get_x_kwargs(self):
        ...
    def get_y_indices_depth_stack(self, wci_nr, y_gridder = None):
        ...
    def get_y_indices_range_stack(self, wci_nr):
        ...
    def get_y_kwargs(self):
        ...
    def iterate_ping_data(self, keep_to_xlimits = True):
        ...
    def reinit(self):
        ...
    def remove_layer(self, name):
        ...
    def set_depth_extent(self, min_depths, max_depths):
        ...
    def set_depth_stack(self, depth_stack = True):
        ...
    def set_linear_mean(self, linear_mean):
        ...
    def set_ping_numbers(self, ping_numbers):
        ...
    def set_ping_times(self, ping_times, time_zone = ...):
        ...
    def set_range_extent(self, min_ranges, max_ranges):
        ...
    def set_range_stack(self, range_stack = True):
        ...
    def set_sample_nr_extent(self, min_sample_nrs, max_sample_nrs):
        ...
    def set_x_axis_date_time(self, min_ping_time = ..., max_ping_time = ..., time_resolution = ..., time_interpolation_limit = ..., max_steps = 4096, **kwargs):
        ...
    def set_x_axis_ping_nr(self, min_ping_nr = 0, max_ping_nr = ..., max_steps = 4096, **kwargs):
        ...
    def set_x_axis_ping_time(self, min_timestamp = ..., max_timestamp = ..., time_resolution = ..., time_interpolation_limit = ..., max_steps = 4096, **kwargs):
        ...
    def set_x_coordinates(self, name, x_coordinates, x_resolution, x_interpolation_limit, vec_x_val):
        ...
    def set_y_axis_depth(self, min_depth = ..., max_depth = ..., max_steps = 1024, **kwargs):
        ...
    def set_y_axis_range(self, min_range = ..., max_range = ..., max_steps = 1024, **kwargs):
        ...
    def set_y_axis_sample_nr(self, min_sample_nr = 0, max_sample_nr = ..., max_steps = 1024, **kwargs):
        ...
    def set_y_axis_y_indice(self, min_sample_nr = 0, max_sample_nr = ..., max_steps = 1024, **kwargs):
        ...
    def set_y_coordinates(self, name, y_coordinates, y_resolution, vec_min_y, vec_max_y):
        ...
