from __future__ import annotations
import datetime as dt
import numpy as np
import themachinethatgoesping as theping
from themachinethatgoesping.pingprocessing.core.progress import get_progress_iterator
__all__ = ['EchoLayer', 'PingData', 'dt', 'get_progress_iterator', 'np', 'theping']
class EchoLayer:
    @classmethod
    def from_ping_param_offsets_absolute(cls, echodata, ping_param_name, offset_0, offset_1):
        ...
    @classmethod
    def from_ping_param_offsets_relative(cls, echodata, ping_param_name, offset_0, offset_1):
        ...
    @classmethod
    def from_static_layer(cls, echodata, min_y, max_y):
        ...
    def __init__(self, echodata, vec_x_val, vec_min_y, vec_max_y):
        ...
    def combine(self, other):
        ...
    def get_y_indices(self, wci_nr):
        ...
class PingData:
    def __init__(self, echodata, nr):
        ...
    def get_datetime(self):
        ...
    def get_extent_layers(self, axis_name = None):
        ...
    def get_limits_layers(self, axis_name = None):
        ...
    def get_ping_time(self):
        ...
    def get_wci(self):
        ...
    def get_wci_layers(self):
        ...
