from themachinethatgoesping.scripts.oceanographic import (
    knots_to_ms as knots_to_ms
)
from themachinethatgoesping.scripts.plot_tools import (
    prepare_plt as prepare_plt
)
from themachinethatgoesping.scripts.sbes import SBES as SBES


pi: float = 3.141592653589793

class MBES:
    def __init__(self, swathopening_angle, beamopening_angle_along, beamopening_angle_across, seafloor_alpha=0, seafloor_beta=0, max_range_factor=2, x=0, y=0, z=0): ...

    def get_seafloor_depth(self, depth, y=None, x=None): ...

    def get_seafloor_y_distance(self, depth, beamangle): ...

    def get_minslant_range(self, depth): ...

    def calc_footprint_along(self, depth: float) -> float: ...

    def calc_footprint_across(self, depth: float) -> float: ...

    def calc_swathwidth(self, depth: float) -> float: ...

    def calc_along_overlap_pingrate(self, speed: float, depth: float) -> float: ...

    @staticmethod
    def calc_along_pingdistance(speed, pingrate): ...

    def calc_along_overlap_depth(self, delta_x): ...

    def calc_along_overlap_depth_for_pingrate(self, speed, pingrate): ...

    def get_swath_ymin_z(self, depth: float) -> float: ...

    def get_swath_ymax_z(self, depth: float) -> float: ...

    def get_swath_limits(self, depth: float) -> tuple: ...

    def get_horizontal_line(self, depth: float, extent=0, ymin=None, ymax=None) -> tuple: ...

    def get_sidelobe_circle(self, depth): ...

    def calc_minslant_bottom_distance(self, depth, y_distance): ...

    def calc_minsland_visible_height(self, depth, y_distance, max_bottom_distance=None): ...

    def calc_linespacing(self, depth, max_minslant_bottom_distance, min_minslant_visible_distance=None, max_flare_height=None): ...

    def plot_along(self, depth, color, add_bottom, axes=None): ...

    def plot_along_pingoverlap_at_pingrate(self, depth, speed, pingrate, color1='r', color2='b', print_vars=True, add_bottom=True, axes=None): ...

    def plot_along_pingoverlap_at_overlapdepth(self, depth, speed, overlapdepth, color1='r', color2='b', print_vars=True, add_bottom=True, axes=None): ...

    def plot_across_swathoverlap_at_linespacing(self, depth, linespacing, max_flare_height=None, color1='orange', color2='purple', print_vars=True, add_bottom=True, axes=None, make_figure=True, limit_plot=True): ...

    def plot_across_swathoverlap_at_max_bottom_distance(self, depth, max_minslant_bottom_distance, min_minslant_visible_height=None, max_flare_height=None, color1='orange', color2='purple', print_vars=True, add_bottom=True, axes=None, make_figure=True, limit_plot=True): ...

    def plot(self, depth, color, add_bottom=True, axes=None, limit_plot=True): ...

    plt_title: str = 'MBES overlap'

    plt_xlabel: str = 'Alongtrack (m)'

    plt_ylabel: str = 'Depth (m)'

    plt_aspect: bool = True

    plt_grid: bool = True

    def make_figure(self, title=None, xlabel=None, ylabel=None, aspect=None, grid=None): ...

    @staticmethod
    def show(): ...
