from __future__ import annotations
from collections import defaultdict
import numpy as np
from themachinethatgoesping.pingprocessing.core.progress import get_progress_iterator
__all__ = ['PingOverview', 'defaultdict', 'get_ping_overview', 'get_progress_iterator', 'np']
class PingOverview:
    def __init__(self, ping_list = None, progress = False):
        ...
    def add_ping(self, ping):
        ...
    def add_ping_list(self, ping_list, progress = False):
        ...
    def get_max(self, key):
        ...
    def get_mean(self, key):
        ...
    def get_median(self, key):
        ...
    def get_min(self, key):
        ...
    def get_minmax(self, key):
        ...
    def get_stat_keys(self):
        ...
def get_ping_overview(ping_list, progress = False):
    ...
