# SPDX-FileCopyrightText: 2022 - 2023 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

python:
#  - 3.8
#  - 3.9
  - 3.10
  - 3.11

cxx_compiler_version:
  - 12 # [linux]

#cxx_compiler:
  #- gxx

#target_platform:
#  - linux-64
