# SPDX-FileCopyrightText: 2022 - 2023 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

python:
#  - 3.10
#  - 3.11
#  - 3.12
  - 3.10

numpy:
  - 1.23

cxx_compiler_version:
  - 12 # [linux]

#cxx_compiler:
  #- gxx

#target_platform:
#  - linux-64
