# SPDX-FileCopyrightText: 2022 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

python:
#  - 3.8
#  - 3.9
  - 3.10

cxx_compiler_version:
  - 11 # [linux]

#cxx_compiler:
  #- gxx

#target_platform:
#  - linux-64
