# SPDX-FileCopyrightText: 2022 - 2023 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

python:
  - 3.11

numpy:
  - 1.26

cxx_compiler_version:
  - 13 # [linux]

#c_compiler_version:
#  - 13 # [linux]

cxx_compiler:
  - clangxx # [linux]
  - clangxx # [osx]
  - clangxx # [win]

host_platform:
 - linux-64

target_platform:
 - linux-64
