# SPDX-FileCopyrightText: 2022 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

{% set name = "themachinethatgoesping" %}
{% set version = "0.0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
  #  - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - pip
    - tomli
    - pyproject-metadata
    - meson>=0.62
  run:
    - python

test:
  imports:
    - themachinethatgoesping

  source_files:
    - subprojects/tools/tests/pytests
  requires:
    - pytest
  commands:
    - pytest

about:
  home: https://themachinethatgoesping.readthedocs.io/en/latest/
  license: MPL-2.0
  summary: Enable advanced processing for multibeam and singlebeam echosounder data.
