# SPDX-FileCopyrightText: 2022 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: cibuildwheel

on:
  push:
    branches: [ main ]    
    paths-ignore:
      - '.github/workflows/ci.yml'
      - '.github/workflows/python-package-windows*'
      - '.github/workflows/python-package-mac*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/ci.yml'
      - '.github/workflows/python-package-windows*'
      - '.github/workflows/python-package-mac*'

jobs:
  cibuildwheel:
      name: Build wheels on ${{ matrix.os }} - ${{ matrix.arch }}
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          #os: [ubuntu-latest, macos-latest]#, windows-2019, macos-10.15]
          include:
            - { os: ubuntu-latest, arch: auto64 }
            - { os: ubuntu-latest, arch: aarch64 }
            - { os: ubuntu-latest, arch: ppc64le }
            - { os: ubuntu-latest, arch: s390x }
            - { os: ubuntu-latest, arch: auto64 }
            - { os: macos-latest,  arch: arm64 }
            - { os: macos-latest,  arch: x86_64 }
            - { os: macos-latest,  arch: universial2 }

      steps:

        - name: checkout main repository
          uses: actions/checkout@v3
          with:
            submodules: recursive

        - uses: actions/setup-python@v2
          name: Install Python
          with:
            python-version: '3.x'

        - name: Set up QEMU
          if: runner.os == 'Linux'
          uses: docker/setup-qemu-action@v2
          with:
            platforms: all

        - name: Build wheels
          uses: pypa/cibuildwheel@v2.6.0
          env:
            # configure cibuildwheel to build native archs ('auto'), and some
            # emulated ones
            # aarch64 did not finish
            #CIBW_ARCHS_LINUX: auto64 aarch64 ppc64le s390x
            CIBW_ARCHS_LINUX: ${{ matrix.arch }}

        - uses: actions/upload-artifact@v2
          with:
            path: ./wheelhouse/*.whl

        - name: Publish package
          # Note 1: In the future the skip existing option should be removed and replaced with the only publish on tags option (if)
          # Note 2: Packages will only be updated when the meson.build version number is changed! (existing will be skipped not upated)
          # Note 3: In the future this should better build against test.pypi repository!
          #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            skip_existing: true
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
            packages_dir: ./wheelhouse/
  
