# SPDX-FileCopyrightText: 2022 - 2023 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: cibuildwheels

on:
  push:
    branches: [ main ]    
    paths-ignore:
      - '.github/workflows/ci.yml'
      - '.github/workflows/python-package-windows*'
      - '.github/workflows/python-package-mac*'
      - '.github/workflows/conda*'
      - '.github/workflows/test_*'
      - 'conda.recipe/*'
      - '*.md'
      - 'doc/*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/ci.yml'
      - '.github/workflows/python-package-windows*'
      - '.github/workflows/python-package-mac*'
      - '.github/workflows/conda*'
      - '.github/workflows/test_*'
      - 'conda.recipe/*'
      - '*.md'
      - 'doc/*'


# make sure that multiple jobs don't run for the same action (new commits cancel old jobs when they are still running)
# Souce Ralf Gommers (commit to meson-python)
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cibuildwheel:
    name: Build wheels on ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, macos-latest]#, windows-2019, macos-10.15]
        include:
          - { os: ubuntu-latest, arch: auto64 }
          #these run very slow at the moment maybe activate for releases
          #- { os: ubuntu-latest, arch: x86_64 }
          #- { os: ubuntu-latest, arch: aarch64 }
          #- { os: ubuntu-latest, arch: ppc64le }
          #- { os: ubuntu-latest, arch: s390x }

          #- { os: macos-latest,  arch: auto64 }
          #- { os: macos-latest,  arch: universal2 }
          - { os: macos-latest,  arch: x86_64}
          #- { os: macos-latest,  arch: arm64}

    steps:

      - name: checkout main repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: false
      
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: tmtgp-cibuildwheels-${{ matrix.arch }}  # name for the cache

      #- uses: actions/setup-python@v2
        #if: runner.os == 'Linux'
        #name: Install Python
        #with:
          #python-version: '3.10'

      # if runner.os 
      - name: Set llvm vers
        if: matrix.os == 'macos-latest'
        run: brew install llvm@14

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          # configure cibuildwheel to build different archs
          MACOSX_DEPLOYMENT_TARGET: "10.15"
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}

      - uses: actions/upload-artifact@v2
        with:
          name: python-package-cibuildwheel
          path: ./wheelhouse/*.whl

      - name: Publish package
        if: runner.os == 'Linux'
        # Note 1: In the future the skip existing option should be removed and replaced with the only publish on tags option (if)
        # Note 2: Packages will only be updated when the meson.build version number is changed! (existing will be skipped not updated)
        # Note 3: In the future this should better build against test.pypi repository!
        #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ./wheelhouse/

  publish_wheels:
    needs: cibuildwheel
    runs-on: ubuntu-latest
    steps:

    - name: Download all the dists
      uses: actions/download-artifact@v2
      with:
        name: python-package-cibuildwheel
        path: dist/

    - name: Publish package
      # Note 1: In the future the skip existing option should be removed and replaced with the only publish on tags option (if)
      # Note 2: Packages will only be updated when the meson.build version number is changed! (existing will be skipped not updated)
      # Note 3: In the future this should better build against test.pypi repository!
      #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: ./dist/
  
