# SPDX-FileCopyrightText: 2022 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Build Python Package macOS

on:
  push:
    branches: [ main ]    
    paths-ignore:
      - '.github/workflows/ci*'
      - '.github/workflows/python-package-linux*'
      - '.github/workflows/python-package-windows*'
      - '.github/workflows/cibuildwheels*'
      - '.github/workflows/conda*'
      - '.github/workflows/test_*'
      - 'conda.recipe/*'
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/ci*'
      - '.github/workflows/python-package-linux*'
      - '.github/workflows/python-package-windows*'
      - '.github/workflows/cibuildwheels*'
      - '.github/workflows/conda*'
      - '.github/workflows/test_*'
      - 'conda.recipe/*'
      - '*.md'

jobs:
  build_wheel:
    name: Build macOS wheel for python${{ matrix.python-version }}

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.8','3.9','3.10']
        compiler: [clang]

    env:
      CC: ${{matrix.compiler}}

    steps:
    - uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python-version}}

    - name: checkout main repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        

    - name: Install dependencies (homebrew)
      run: |
          brew install boost libomp

    #same as on linux
    - name: Install dependencies (pip)
      run: |
        pip install --upgrade pip
        pip install meson ninja pytest twine wheel pyproject-metadata delocate pep517
         
    - name: build and install wheel
      run: |
        # build wheel
        pip wheel -w dist . --no-deps -v --config-settings="builddir=pybuild" #--no-build-isolation
        # delocate wheel
        delocate-wheel -w wheelhouse dist/* -v
        # install wheel
        pip install wheelhouse/*
        #pip install . --config-settings="builddir=pybuild" --no-build-isolation
        
    - name: Store the binary wheel
      uses: actions/upload-artifact@v3
      with:
        name: python-package-macos
        path: wheelhouse
         
    - name: Test with meson (c++)
      run: |
        meson test -C pybuild
        
    - name: Test with pytest
      run: |
        pytest -v
        
  install_and_test:
    name: Install and test macOS wheel for python 3.${{ matrix.python-3-version }}
    needs: build_wheel
    runs-on: macos-latest

    strategy:
      matrix:
        python-3-version: ['8','9','10']

    steps:    
    
    - uses: actions/setup-python@v3
      with:
        python-version: 3.${{matrix.python-3-version}}
    
    #necessary only for pytest
    - name: checkout main repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Download all the dists
      uses: actions/download-artifact@v2
      with:
        name: python-package-macos
        path: dist/
        
    - name: install pip dependencies
      run: pip install pytest
      
    - name: install wheels
      run: |
        pip install $(ls dist/*-cp3${{matrix.python-3-version}}-*.whl)
        
    - name: test (pytest)
      run: pytest
    
  publish_wheels:
    needs: install_and_test
    runs-on: ubuntu-latest
    steps:
    
    - name: Download all the dists
      uses: actions/download-artifact@v2
      with:
        name: python-package-macos
        path: dist/
        
    - name: Publish package
      # Note 1: In the future the skip existing option should be removed and replaced with the only publish on tags option (if)
      # Note 2: Packages will only be updated when the meson.build version number is changed! (existing will be skipped not upated)
      # Note 3: In the future this should better build against test.pypi repository!
      #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: ./dist/

  # delay for one minute before attempting to download the packages from pypi
  delay_after_publish:
    needs: publish_wheels
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 60 seconds
      run: sleep 60s
      shell: bash

  test_pypi:
    needs: delay_after_publish
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8','3.9','3.10']
      
    steps:    
    - name: checkout main repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python-version}}

    - name: install via pip
      run: pip install themachinethatgoesping pytest

    - name: pytest from git repo
      run: pytest -v
      
