# SPDX-FileCopyrightText: 2022 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

name: Test_PyPi

on:
  push:
    branches: [ main ]
    
    paths-ignore:
      - '.github/workflows/python-package*'
      - '.github/workflows/ci*'
      - '.github/workflows/conda*'
      - 'conda.recipe/*'
    #paths:
    #  - "**meson.build"
    #  - "**.cpp"
    #  - "**.c"
    #  - "**.h"
  pull_request:
    branches: [ main ]
    
    paths-ignore:
      - '.github/workflows/python-package*'
      - '.github/workflows/ci*'
      - '.github/workflows/conda*'
      - 'conda.recipe/*'
    #paths:
    #  - "**meson.build"
    #  - "**.cpp"
    #  - "**.c"
    #  - "**.h"

# env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  #BUILD_TYPE: Release
  
jobs:
  install_pip:
    name: Python ${{matrix.python_version}} on ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: ['3.8','3.9','3.10']
  
    runs-on: ${{matrix.os}}

    steps:
    - name: checkout main repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python_version}}

    - name: install via pip
      run: pip install themachinethatgoesping pytest

    - name: pytest from git repo
      run: pytest -v
      
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: ${{matrix.container}}_Testlog
        path: builddir/meson-logs/testlog.txt
    
  install_container:
    name: Python ${{matrix.python_version}} on ${{matrix.container}}
    strategy:
      fail-fast: false
      matrix:       

        include:  
          - { container: 'ubuntu:22.04', 
              pre-dep : 'apt update && apt-get install -y sudo git',
              python_version: ['3.8','3.9','3.10']}
          - { container: 'archlinux', 
              pre-dep : 'pacman -Syu --noconfirm; pacman -Syy sudo git --noconfirm',
              python_version: ['3.8','3.9','3.10']}
  
    runs-on: ubuntu-latest
    container: ${{matrix.container}}

    steps:
    - name: install prequisits
      if:  ${{matrix.pre-dep}}
      run: ${{matrix.pre-dep}}

    - name: checkout main repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python_version}}

    - name: install via pip
      run: python -m pip install setuptools themachinethatgoesping pytest

    - name: python -m pytest from git repo
      run: pytest -v
      
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: ${{matrix.container}}_Testlog
        path: builddir/meson-logs/testlog.txt
    

    
      
