{% set name = "themachinethatgoesping" %}
{% set version = "0.0.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - meson>=1.0
    - ninja
    - {{ compiler('cxx') }}
  host:
    - pip
    - python >=3.8
    - tomli
    - pyproject-metadata
    - numpy
    - boost-cpp
  run:
    - python >=3.8
    - numba
    - {{ pin_compatible('numpy') }}
    - tqdm

test:
  imports:
    - themachinethatgoesping

  source_files:
    - subprojects/tools/python/tests
    - subprojects/echosounders/python/tests
    - subprojects/navigation/python/tests
    - subprojects/gridding/python/tests
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest

about:
  home: https://github.com/themachinethatgoesping
  summary: Enable advanced processing for multibeam and singlebeam echosounder data.THIS PROJECT IS IN DEVELOPMENT. NO useful FUNCTIONALITY EXISTS SO FAR!
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - urp
