{% set name = "themachinethatgoesping" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../

build:
  #noarch: python-m 
  script: pip install . -v --config-settings=setup-args="-Ddynamic_boost=enabled"
  number: 0
  script_env:
    - BOOST_ROOT={{ PREFIX }}/

requirements:
  build:
    - meson>=1.4
    - meson-python
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkgconfig
    - pip
    - boost
    - python
    - numpy<2.0
    - pkg-config
    - cmake
    - curl
  host:
    - boost-cpp
    - python
    - numpy<2.0
# "build" packages picked up binutis 2.39 for gcc, but the "host" package picked up binutils 2.40 for python.
#   Force host to use same binutils as build by including them in here.
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  run:
    - python
    - numba
    - {{ pin_compatible('numpy') }}
    - tqdm
    - rasterio
    - matplotlib

test:
  imports:
    - themachinethatgoesping

  source_files:
    - subprojects/tools/python/tests
    - subprojects/navigation/python/tests
    - subprojects/algorithms/python/tests
    - subprojects/echosounders/python/tests
    - subprojects/pingprocessing/python/tests
    - subprojects/gridding/python/tests
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest

about:
  home: https://github.com/themachinethatgoesping
  summary: Enable advanced processing for multibeam and singlebeam echosounder data.THIS PROJECT IS IN DEVELOPMENT.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Peter Urban
